{"content": {"suites": {"0": {"status": {"total_pass": 4, "total_skip": 0, "total_xpass": 0, "total_xfail": 0, "total_rerun": 0, "total_fail": 3, "total_error": 1}, "tests": {"0": {"status": "PASS", "message": "", "test_name": "test_log", "rerun": "0"}, "1": {"status": "PASS", "message": "", "test_name": "test_log", "rerun": "0"}, "2": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f1f5dd89460>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=54873): Max retries exceeded with url: /session/e27909b14ee7f1841770fcc877c9c85e/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f5dd89460>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_login", "rerun": "0"}, "3": {"status": "FAIL", "message": "   NameError: name 'mysql' is not defined\n", "test_name": "test_database", "rerun": "0"}, "4": {"status": "PASS", "message": "", "test_name": "test_log", "rerun": "0"}, "5": {"status": "FAIL", "message": "           ConnectionRefusedError: [Errno 111] Connection refused\n       urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f1f5d804f40>: Failed to establish a new connection: [Errno 111] Connection refused\n       urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=50765): Max retries exceeded with url: /session/7c6bb95723cbb076adf78169babca780/url (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f1f5d804f40>: Failed to establish a new connection: [Errno 111] Connection refused'))\n", "test_name": "test_login", "rerun": "0"}, "6": {"status": "ERROR", "message": "file /home/praveenyadav/Desktop/p.collegedekho-1/CTA/setting.py, line 5\n  def test_setting(self):\nE       fixture 'self' not found\n>       available fixtures: LineMatcher, _config_for_test, _pytest, _sys_snapshot, cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, include_metadata_in_junit_xml, linecomp, metadata, monkeypatch, pytestconfig, pytester, record_property, record_testsuite_property, record_xml_attribute, recwarn, sb, setup, testdir, testrun_uid, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory, worker_id\n>       use 'pytest --fixtures [testpath]' for help on them.\n\n/home/praveenyadav/Desktop/p.collegedekho-1/CTA/setting.py:5\n", "test_name": "test_setting", "rerun": "0"}, "7": {"status": "PASS", "message": "", "test_name": "test_log", "rerun": "0"}}, "suite_name": "test_deskhomepage.py"}}}, "date": "September 01, 2022", "start_time": 1662018132.0661216, "total_suite": 1, "status": "FAIL", "status_list": {"pass": "4", "fail": "3", "skip": "0", "error": "1", "xpass": "0", "xfail": "0", "rerun": "0"}, "total_tests": "8"}